### ISSUE TITLE
flake8 should ignore generated test script files

### ISSUE THREAD

**Issue by sgbaird** [sgbaird/honegumi#6]
in precommit config file

**Comment by sgbaird** [comment]
Fixed:
```yaml
- repo: https://github.com/PyCQA/flake8
  rev: 6.0.0
  hooks:
  - id: flake8
    exclude: ^tests/generated_scripts/
```
https://github.com/sgbaird/honegumi/pull/4
